

PartNumber.create!([
  {name: "50-1467", sort: 0, active_status: 0},
  {name: "50-3627", sort: 0, active_status: 0},
  {name: "50-1437", sort: 0, active_status: 0},
  {name: "50-3632", sort: 0, active_status: 0},
  {name: "50-6686", sort: 0, active_status: 0},
  {name: "50-6729", sort: 0, active_status: 0},
  {name: "50-1858", sort: 0, active_status: 0},
  {name: "50-4748", sort: 0, active_status: 0},
  {name: "50-1448", sort: 0, active_status: 0},
  {name: "50-9341", sort: 0, active_status: 0},
  {name: "50-9641", sort: 0, active_status: 0},
  {name: "50-1713", sort: 0, active_status: 0},
  {name: "50-5710", sort: 0, active_status: 0},
  {name: "50-0786", sort: 0, active_status: 0},
  {name: "50-1731", sort: 0, active_status: 0},
  {name: "50-2407", sort: 0, active_status: 0},
  {name: "50-2421", sort: 0, active_status: 0},
  {name: "50-4916", sort: 0, active_status: 0},
  {name: "50-4900", sort: 0, active_status: 0}
])

ProcessStep.create!([
  {name: "Compact Plate", sort: 0, active_status: 0},
  {name: "Compact Pedestal", sort: 0, active_status: 0},
  {name: "Assemble & Sinter", sort: 0, active_status: 0},
  {name: "OP 10 Turning", sort: 0, active_status: 0},
  {name: "OP 20 Turning", sort: 0, active_status: 0},
  {name: "OP 30 Broach", sort: 0, active_status: 0},
  {name: "OP 40 Turn, Drill & Ream", sort: 0, active_status: 0},
  {name: "OP 50 Hobbing", sort: 0, active_status: 0},
  {name: "OP 60 Balance", sort: 0, active_status: 0},
  {name: "OP 70 Deburr", sort: 0, active_status: 0},
  {name: "OP 80 HP Wash/Wash/Media", sort: 0, active_status: 0},
  {name: "OP 90 Final Inspection", sort: 0, active_status: 0}
])


QuestionList.create!([
  {name: "Are Process Sheets present (if required)?", partnumberguide: "basic", sort: 30, active_status: 1},
  {name: "Is the First off completed correctly and is it signed off (if required)?", partnumberguide: "basic", sort: 50, active_status: 1},
  {name: "Is Operator following the SWI properly (if applicable)?", partnumberguide: "basic", sort: 70, active_status: 1},
  {name: "Does the OIS show the operator is doing all required checks (if required)?", partnumberguide: "basic", sort: 90, active_status: 1},
  {name: "Ask the operator to measure a feature and record the feature number and measurement value here (like this:  98, 2.346)?", partnumberguide: "basic", sort: 110, active_status: 1},
  {name: "Are gauges defined on the process sheet at the station (if required)? Record numbers below.", partnumberguide: "basic", sort: 130, active_status: 1},
  {name: "Are Traceability Tags completed properly?", partnumberguide: "basic", sort: 150, active_status: 1},
  {name: "If present, is operator aware of and following any QA/SI/TPC notices?", partnumberguide: "basic", sort: 170, active_status: 1},
  {name: "If present, are error proofing parts (red rabbits) available, has error proofing been verified and are the red rabbits stored in the designated storage location (i.e. Hooks, shelf etc...)?", partnumberguide: "basic", sort: 190, active_status: 1},
  {name: "What Part Number are you auditing?", partnumberguide: "basic", sort: 210, active_status: 1},
  {name: "What operation are you auditing?", partnumberguide: "basic", sort: 230, active_status: 1},
  {name: "Is there evidence that operators are stapling the OIS to the first off?", partnumberguide: "all parts", sort: 250, active_status: 1},
  {name: "[Compact] Ensure there is no oil dripping onto press bed in or close to path of powder shoe.", partnumberguide: "Common to Parts (50-1437, 50-5710, 50-1467, 50-9341, 50-0455, 50-0786, 50-1731, 50-3632, 50-1713, 50-3627, 50-1858, 50-1448, 50-9641)", sort: 270, active_status: 1},
  {name: "Are the proper ring test red rabbits for the part being run, hanging on the designated hooks at the workstation?", partnumberguide: "Common to Parts (50-1437, 50-5710, 50-1467, 50-9341, 50-0455, 50-0786, 50-1731, 50-3632, 50-1713, 50-3627, 50-1858, 50-1448, 50-9641)", sort: 290, active_status: 1},
  {name: "Is the ring test verification documented on the Verification Log at the prescribed frequency?", partnumberguide: "Common to Parts (50-1437, 50-5710, 50-1467, 50-9341, 50-0455, 50-0786, 50-1731, 50-3632, 50-1713, 50-3627, 50-1858, 50-1448, 50-9641)", sort: 310, active_status: 1},
  {name: "Is operator ring testing parts 100%?", partnumberguide: "Common to Parts (50-1437, 50-5710, 50-1467, 50-9341, 50-0455, 50-0786, 50-1731, 50-3632, 50-1713, 50-3627, 50-1858, 50-1448, 50-9641)", sort: 330, active_status: 1},
  {name: "Is the  automatic weigh scale verification being done at required frequency?", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 350, active_status: 1},
  {name: "Ensure grippers are picking part up parallel to press bed (should be approx. 1/4 inch gap between press bed and part when part is in the grippers).", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 370, active_status: 1},
  {name: "Ensure there is no powder on spline face and that execss powder wiper and blow off are functioning (should be no excess powder on spline face).", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 390, active_status: 1},
  {name: "Are hardening faulted parts being recorded on the log sheet and placed in the red bin ?", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 410, active_status: 1},
  {name: "Is the fault, time and shift being written on the faulted parts that are in the red bin?", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 430, active_status: 1},
  {name: "Are the stamps from induction legible on parts (Optimize Line: 1 & 2 Trilobe Line: 3 & 4)", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 450, active_status: 1},
  {name: "Is the induction overflow bin labeled with a placard that says \"Operation Completed: INDUCTION\"?", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 470, active_status: 1},
  {name: "Is case depth being verified and are results logged in the database regularly (see Team Leader)?", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 490, active_status: 1},
  {name: "Is the cell free of any loose or stray parts?", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 510, active_status: 1},
  {name: "Are the wash nozzles on the slurry arm aimed correctly (pointing at the pinion holes) and spraying the parts with enough force to remove machining chips and deburr media?", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 530, active_status: 1},
  {name: "Are all rejects getting recorded on the tally sheet and placed in the red bin", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 550, active_status: 1},
  {name: "Is the failure mode being written on the reject parts that are in the red bin?", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 570, active_status: 1},
  {name: "Is the operator following the SWI Sequence", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 590, active_status: 1},
  {name: "Are parts Julian date stamped and legible?", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 610, active_status: 1},
  {name: "Is the error verification log filled out for the hole position gauge?", partnumberguide: "Common to 50-1437, 50-5710, 50-1467, 50-9341, 50-0455", sort: 630, active_status: 1}
])


Question.create!([
  {title_notused: "", survey_id: 7, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 2, active_status: nil, sort: nil},
  {title_notused: nil, survey_id: 1, qtype: "select_yes_no", question_note: "special note for q1", question_whatlookfor: nil, question_if_no: nil, question_list_id: 1, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 2, qtype: "select_part_number", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 10, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 4, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 1, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 4, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 2, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 7, qtype: "select_yes_no", question_note: "Verify first off has all required information; manual data entered on sheet, nothing out of tolerance, TPC (if features are out of tolerance), CMM reports attached and FO is signed off.", question_whatlookfor: "Look for: \r\n - Process sheet has all manual entry data fields filled in and is within tolerance\r\n - CMM report is attached to the first off and all data is within tolerance limits\r\n - If out of tolerance, is a TPC issued\r\n - Ensure TPC covers out of tolerance features", question_if_no: "- Missing data; have feature measured by operator, if within\r\n   tolerance have operator complete first off sheet by entering\r\n   missing data\r\n - Missing CMM report; have operator submit parts for CMM\r\n   measurement. Ensure all features on CMM report are within\r\n   tolerance limits, attach to first off\r\n - Measured feature out of tolerance then follow non-conforming\r\n   procedure SWI-000824\r\n      - Contain material between last good check and time of\r\n        finding and generate a hold tag or;\r\n      - Generate a TPC to cover the out of tolerance condition\r\n        (if warranted).", question_list_id: 2, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 7, qtype: "select_part_number", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 10, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "select_part_number", question_note: "", question_whatlookfor: "- Correct process sheet is at the workstation or hanging on the\r\n   machine", question_if_no: "- Acquire correct process sheet and post at station\r\n - Show operator where to get correct process sheet (Windchill)", question_list_id: 10, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "short_answer", question_note: "Enter the operation you are auditing. (zz)", question_whatlookfor: "", question_if_no: "", question_list_id: 11, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "select_yes_no", question_note: "(Verify process sheets are at the workstation or hanging on the machine)", question_whatlookfor: "", question_if_no: "", question_list_id: 1, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "select_yes_no", question_note: "Verify first off has all required information; manual data entered on sheet, nothing out of tolerance, TPC (if features are out of tolerance), CMM reports attached and is signed off.", question_whatlookfor: "", question_if_no: "", question_list_id: 2, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "select_yes_no", question_note: "Verify operator is following the process steps outlined in the SWI, watch what they do.", question_whatlookfor: "", question_if_no: "", question_list_id: 3, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "select_yes_no", question_note: "Pick a manually measured feature on the process sheet and have the operator perform the inspection. Check that they are using the proper gauge and that they measure it correctly.", question_whatlookfor: "", question_if_no: "", question_list_id: 4, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "short_answer", question_note: "Record the feature number and measured value in the space provided (like this:98, 2.346).", question_whatlookfor: "", question_if_no: "", question_list_id: 5, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "select_yes_no", question_note: "Verify that all gauges listed on the process sheet are at the workstation for operator use. ", question_whatlookfor: "", question_if_no: "", question_list_id: 6, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "short_answer", question_note: "Record the gauge numbers in the space provided (Like this: SDG-402, DHG-12, MO1-392)", question_whatlookfor: "", question_if_no: "", question_list_id: 6, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "select_yes_no", question_note: "Ensure the trace tag is filled out at the start of the bin not when the bin is complete.", question_whatlookfor: "", question_if_no: "", question_list_id: 7, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "select_yes_no", question_note: "Verify operator awareness by asking them about any issues they are aware of and then reviewing any alerts, TPC's, SI's posted at the workstation to see if they match.", question_whatlookfor: "", question_if_no: "", question_list_id: 8, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 8, qtype: "select_yes_no", question_note: "Verify that error proofing checks have been completed and that all required red rabbits are available and in their proper location. If one is missing there should be and orange tag in place to show that the red rabbit is in QA Lab for repair.", question_whatlookfor: "", question_if_no: "", question_list_id: 9, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_part_number", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 10, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "short_answer", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 11, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "Verify process sheets are at the workstation or hanging on the machine.", question_whatlookfor: "", question_if_no: "", question_list_id: 1, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "Verify first off has all required information; manual data entered on sheet, nothing out of tolerance, TPC (if features are out of tolerance), CMM reports attached and is signed off.", question_whatlookfor: "", question_if_no: "", question_list_id: 2, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "Verify operator is following the process steps outlined in the SWI, watch what they do.", question_whatlookfor: "", question_if_no: "", question_list_id: 3, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "Pick a manually measured feature on the process sheet and have the operator perform the inspection. Check that they are using the proper gauge and that they measure it correctly.", question_whatlookfor: "", question_if_no: "", question_list_id: 4, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "short_answer", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 5, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "short_answer", question_note: "Verify that all gauges listed on the process sheet are at the workstation for operator use. Record all the gauge numbers here (like this: DHG-123, SP-112).", question_whatlookfor: "", question_if_no: "", question_list_id: 6, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "Ensure the trace tag is filled out at the start of the bin not when the bin is complete.", question_whatlookfor: "", question_if_no: "", question_list_id: 7, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "Verify operator awareness by asking them about any issues they are aware of and then reviewing any alerts, TPC's, SI's posted at the workstation to see if they match.", question_whatlookfor: "", question_if_no: "", question_list_id: 8, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "Verify that error proofing checks have been completed and that all required red rabbits are available and in their proper location. If one is missing there should be and orange tag in place to show that the red rabbit is in QA Lab for repair. Verify a TPC has been written and posted.", question_whatlookfor: "", question_if_no: "", question_list_id: 9, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "Ensure OIS sheets are being stapled to the first off / last off.", question_whatlookfor: "", question_if_no: "", question_list_id: 12, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 17, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 13, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 18, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 19, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 14, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 15, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 20, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 21, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 22, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 23, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 24, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 25, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 26, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 27, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 28, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 29, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 30, active_status: 0, sort: 0},
  {title_notused: "", survey_id: 9, qtype: "select_yes_no", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 31, active_status: 0, sort: 0},
  {title_notused: nil, survey_id: 5, qtype: "select_yes_no", question_note: "12:58PM", question_whatlookfor: nil, question_if_no: nil, question_list_id: 1, active_status: 0, sort: 14},
  {title_notused: "", survey_id: 1, qtype: "short_answer", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 5, active_status: 0, sort: 20},
  {title_notused: nil, survey_id: 6, qtype: "select_yes_no", question_note: "12:28PM 2017-05-17_Wed_12.28-PM", question_whatlookfor: nil, question_if_no: nil, question_list_id: 2, active_status: 0, sort: 20},
  {title_notused: "", survey_id: 6, qtype: "short_answer", question_note: "Rf", question_whatlookfor: "V ", question_if_no: "Gh", question_list_id: 26, active_status: 1, sort: 30},
  {title_notused: "", survey_id: 1, qtype: "short_answer", question_note: "", question_whatlookfor: "", question_if_no: "", question_list_id: 4, active_status: 0, sort: 111}
])
Survey.create!([
  {title: "Basic LPA test2", user_id: 4, active_status: 0, sort: 0},
  {title: "t10", user_id: 4, active_status: 0, sort: 0},
  {title: "t12", user_id: 4, active_status: 0, sort: 0},
  {title: "t14", user_id: 4, active_status: 0, sort: 0},
  {title: "Test LPA", user_id: 5, active_status: 0, sort: 0},
  {title: "Basic Supervisor LPA", user_id: 5, active_status: 0, sort: 0},
  {title: "QE/Production Manager/Senior Management LPA", user_id: 5, active_status: 0, sort: 0}
])

Answer.create!([
  {body: "{\"yes_no\":\"No\",\"issue_description\":\"x\",\"action_taken\":\"y\"}", user_id: 4, question_id: 1, issue_description: "x", action_taken: "y", survey_id: nil},
  {body: "{\"yes_no\":\"No\",\"issue_description\":\"i\",\"action_taken\":\"a\"}", user_id: 2, question_id: nil, issue_description: "i", action_taken: "a", survey_id: nil},
  {body: "{\"yes_no\":\"No\",\"issue_description\":\"ii\",\"action_taken\":\"aa\"}", user_id: 2, question_id: 1, issue_description: "ii", action_taken: "aa", survey_id: nil},
  {body: "{\"yes_no\":\"Yes\",\"issue_description\":\"a\",\"action_taken\":\"b\"}", user_id: 2, question_id: 1, issue_description: "a", action_taken: "b", survey_id: nil},
  {body: "{\"yes_no\":\"No\",\"issue_description\":\"c\",\"action_taken\":\"d\"}", user_id: 2, question_id: 1, issue_description: "c", action_taken: "d", survey_id: nil},
  {body: "{\"yes_no\":\"No\",\"issue_description\":\"e\",\"action_taken\":\"f\"}", user_id: 2, question_id: 1, issue_description: "e", action_taken: "f", survey_id: nil},
  {body: "{\"issue_description\":\"i\",\"action_taken\":\"\"}", user_id: 2, question_id: 1, issue_description: "i", action_taken: "", survey_id: 1},
  {body: "{\"yes_no\":\"No\",\"issue_description\":\"2\",\"action_taken\":\"3\"}", user_id: 4, question_id: 1, issue_description: "2", action_taken: "3", survey_id: 1},
  {body: "a", user_id: 4, question_id: 3, issue_description: nil, action_taken: nil, survey_id: nil},
  {body: "a", user_id: 4, question_id: 2, issue_description: nil, action_taken: nil, survey_id: nil},
  {body: "{\"yes_no\":\"Yes\",\"issue_description\":\"4\",\"action_taken\":\"5\"}", user_id: 4, question_id: 1, issue_description: "4", action_taken: "5", survey_id: 1},
  {body: "6", user_id: 4, question_id: 3, issue_description: nil, action_taken: nil, survey_id: nil},
  {body: "7", user_id: 4, question_id: 2, issue_description: nil, action_taken: nil, survey_id: nil},
  {body: "{\"yes_no\":\"No\",\"issue_description\":\"\",\"action_taken\":\"\"}", user_id: 4, question_id: 1, issue_description: "", action_taken: "", survey_id: 1},
  {body: "d", user_id: 4, question_id: 3, issue_description: nil, action_taken: nil, survey_id: nil},
  {body: "d", user_id: 4, question_id: 2, issue_description: nil, action_taken: nil, survey_id: nil},
  {body: "{\"yes_no\":\"No\",\"issue_description\":\"\",\"action_taken\":\"\"}", user_id: 4, question_id: 1, issue_description: "", action_taken: "", survey_id: 1},
  {body: "a", user_id: 4, question_id: 3, issue_description: nil, action_taken: nil, survey_id: nil},
  {body: "a", user_id: 4, question_id: 2, issue_description: nil, action_taken: nil, survey_id: nil},
  {body: "{\"yes_no\":\"No\",\"issue_description\":\"\",\"action_taken\":\"\"}", user_id: 4, question_id: 1, issue_description: "", action_taken: "", survey_id: 1},
  {body: "a", user_id: 4, question_id: 3, issue_description: nil, action_taken: nil, survey_id: nil},
  {body: "a", user_id: 4, question_id: 2, issue_description: nil, action_taken: nil, survey_id: nil},
  {body: "No", user_id: 4, question_id: 1, issue_description: "4", action_taken: "5", survey_id: 1},
  {body: "6", user_id: 4, question_id: 3, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "7", user_id: 4, question_id: 2, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "50-6686", user_id: 4, question_id: 4, issue_description: nil, action_taken: nil, survey_id: 2},
  {body: "Yes", user_id: 4, question_id: 1, issue_description: ".", action_taken: ".", survey_id: 1},
  {body: "a", user_id: 4, question_id: 3, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "a", user_id: 4, question_id: 2, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "Yes", user_id: 4, question_id: 1, issue_description: ".", action_taken: ".", survey_id: 1},
  {body: "Hj", user_id: 4, question_id: 2, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "Yes", user_id: 4, question_id: 3, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "Yes", user_id: 4, question_id: 1, issue_description: ".", action_taken: ".", survey_id: 1},
  {body: "23, 0.1232", user_id: 4, question_id: 2, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "Yes", user_id: 4, question_id: 3, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "Yes", user_id: 4, question_id: 1, issue_description: "H", action_taken: ".", survey_id: 1},
  {body: "I", user_id: 4, question_id: 2, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "Yes", user_id: 4, question_id: 3, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "Yes", user_id: 5, question_id: 1, issue_description: "none", action_taken: "none", survey_id: 1},
  {body: "39, 2.443", user_id: 5, question_id: 2, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "Yes", user_id: 5, question_id: 3, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "50-6686", user_id: 5, question_id: 4, issue_description: nil, action_taken: nil, survey_id: 2},
  {body: "Yes", user_id: 5, question_id: 5, issue_description: "none", action_taken: "", survey_id: 3},
  {body: "Yes", user_id: 5, question_id: 6, issue_description: "none", action_taken: "none", survey_id: 4},
  {body: "Yes", user_id: 5, question_id: 7, issue_description: "none", action_taken: "none", survey_id: 4},
  {body: "Yes", user_id: 5, question_id: 8, issue_description: "none", action_taken: "none", survey_id: 5},
  {body: "Yes", user_id: 5, question_id: 9, issue_description: "none", action_taken: "none", survey_id: 6},
  {body: "yes", user_id: 5, question_id: 10, issue_description: nil, action_taken: nil, survey_id: 6},
  {body: "Yes", user_id: 5, question_id: 1, issue_description: "none", action_taken: "", survey_id: 1},
  {body: "25, 1.447", user_id: 5, question_id: 2, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "yes", user_id: 5, question_id: 3, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "Yes", user_id: 5, question_id: nil, issue_description: "none", action_taken: "", survey_id: 7},
  {body: "No", user_id: 5, question_id: nil, issue_description: "none", action_taken: "", survey_id: 7},
  {body: "No", user_id: 5, question_id: 12, issue_description: "missing data for feature 29", action_taken: "notified supervisor of issue, had operator measure feature 29 on a part and it was within tolerance - no risk. F/O data updated.", survey_id: 7},
  {body: "50-4916", user_id: 5, question_id: 13, issue_description: nil, action_taken: nil, survey_id: 7},
  {body: "Yes", user_id: 5, question_id: 11, issue_description: "none", action_taken: "na", survey_id: 7},
  {body: "Yes", user_id: 5, question_id: 12, issue_description: "none", action_taken: "na", survey_id: 7},
  {body: "50-4748", user_id: 5, question_id: 13, issue_description: nil, action_taken: nil, survey_id: 7},
  {body: "Yes", user_id: 5, question_id: 1, issue_description: "none", action_taken: "na", survey_id: 1},
  {body: "45a, 4.325", user_id: 5, question_id: 2, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "yes", user_id: 5, question_id: 3, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "50-3632", user_id: 5, question_id: 14, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "OP 10 Turning", user_id: 5, question_id: 15, issue_description: "", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 16, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 17, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 18, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 19, issue_description: "", action_taken: "", survey_id: 8},
  {body: "113, 0.447", user_id: 5, question_id: 20, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 21, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "MO1-428, SG-444, RG-258", user_id: 5, question_id: 22, issue_description: "", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 23, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 24, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 25, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "50-3632", user_id: 5, question_id: 14, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 16, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 17, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 18, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 19, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "78, 3.44", user_id: 5, question_id: 20, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 21, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "SDG-441, FG-34, CMM-22", user_id: 5, question_id: 22, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 23, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 24, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 25, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "50-0786", user_id: 5, question_id: 14, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "100% Inspection", user_id: 5, question_id: 15, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 16, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 17, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 18, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 19, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "117, 14.064", user_id: 5, question_id: 20, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 21, issue_description: "none", action_taken: "", survey_id: 8},
  {body: "SDG-502", user_id: 5, question_id: 22, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 23, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 24, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "No", user_id: 5, question_id: 25, issue_description: "Error proofing checks not completed at specified frequency.", action_taken: "Spoke to operator regarding importance of error proofing check being completed per frequency specified. Had operator perform checks and sign off sheet.", survey_id: 8},
  {body: "50-3632", user_id: 5, question_id: 14, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Op 10", user_id: 5, question_id: 15, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 16, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 17, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 18, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 19, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "G, 0.074", user_id: 5, question_id: 20, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 21, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "RG-632, FF-313, FF-310, M-330, DHG-11, SP-01", user_id: 5, question_id: 22, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 23, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 24, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 25, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "50-3627", user_id: 5, question_id: 14, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Compact", user_id: 5, question_id: 15, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 16, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 17, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 18, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 19, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "D, 606.6", user_id: 5, question_id: 20, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 21, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "BM-55, M01-413, DI-119, SC-6680", user_id: 5, question_id: 22, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 23, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 24, issue_description: "", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 25, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "50-6729", user_id: 5, question_id: 14, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Op 10", user_id: 5, question_id: 15, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 16, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "No", user_id: 5, question_id: 17, issue_description: "Feature 135 not completed on first off. ", action_taken: "Notified supervisor of issue. Operator measured feature 135 and it was within tolerance. Completed first off. ", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 18, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 19, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "135, 81.143", user_id: 5, question_id: 20, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 21, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Sterling gauge (no number on gauge)", user_id: 5, question_id: 22, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 23, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 24, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 25, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "50-1858", user_id: 5, question_id: 14, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Op 10", user_id: 5, question_id: 15, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 16, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 17, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 18, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 19, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "20, 5.03", user_id: 5, question_id: 20, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 21, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "RM-1, DHG-5, M01-392, SDG-205, CMM-22", user_id: 5, question_id: 22, issue_description: nil, action_taken: nil, survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 23, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 24, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "Yes", user_id: 5, question_id: 25, issue_description: "None", action_taken: "", survey_id: 8},
  {body: "50-1467", user_id: 5, question_id: 26, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "OP 10", user_id: 5, question_id: 27, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 28, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 29, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 30, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 31, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "19, 15.257", user_id: 5, question_id: 32, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "CH-12, SDG-669-3, RM-1, PG-1762, PG-2192, SDG-630", user_id: 5, question_id: 33, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "No", user_id: 5, question_id: 34, issue_description: "Trace tag not attached to the bin.", action_taken: "Spoke to operator regarding importance of completing the trace tag and attaching it to the bin at the start of his shift. Trace tag completed and attached to bin.", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 35, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 36, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 37, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 38, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 39, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 40, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 41, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 42, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 43, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 44, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "No", user_id: 5, question_id: 45, issue_description: "Many parts in red scrap container not identified and not documented on the log sheet per requirements.", action_taken: "Notified on-shift supervision of issue. Supervisor re-instructed operator on importance of documenting faults on the parts and also completing the log sheet properly.", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 46, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 47, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 48, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 49, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 50, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 51, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 52, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 53, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 54, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 55, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "50-1437", user_id: 5, question_id: 26, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "OP 10", user_id: 5, question_id: 27, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 28, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 29, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 30, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 31, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "19, 15.254", user_id: 5, question_id: 32, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "CH-12, SDG-457, PG-1234, RM-1", user_id: 5, question_id: 33, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 34, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 35, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 36, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 37, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 38, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 39, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 40, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 41, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 42, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 43, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 44, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 45, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 46, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 47, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 48, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 49, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 50, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 51, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 52, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 53, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 54, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 5, question_id: 55, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "No", user_id: 4, question_id: 1, issue_description: "d", action_taken: "d", survey_id: 1},
  {body: "93", user_id: 4, question_id: 2, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "wer", user_id: 4, question_id: 3, issue_description: nil, action_taken: nil, survey_id: 1},
  {body: "50-1437", user_id: 6, question_id: 26, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "Machining", user_id: 6, question_id: 27, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "Yes", user_id: 6, question_id: 28, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 6, question_id: 29, issue_description: "Machine down fo maintenance. Fo and lo present and correct", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 6, question_id: 30, issue_description: "None", action_taken: "", survey_id: 9},
  {body: "Yes", user_id: 6, question_id: 31, issue_description: "Non", action_taken: "", survey_id: 9},
  {body: "Not running", user_id: 6, question_id: 32, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "50-5810 pg-1446 sg 55. Eg ", user_id: 6, question_id: 33, issue_description: nil, action_taken: nil, survey_id: 9},
  {body: "No", user_id: 6, question_id: 34, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 35, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 36, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 37, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 38, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 39, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 40, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 41, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 42, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 43, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 44, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 45, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 46, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 47, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 48, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 49, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 50, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 51, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 52, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 53, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 54, issue_description: "", action_taken: "", survey_id: 9},
  {body: "No", user_id: 6, question_id: 55, issue_description: "", action_taken: "", survey_id: 9}
])
